language: elixir
elixir:
  - 1.3.2
install:
  - MIX_ENV=test mix local.rebar --force
  - MIX_ENV=test mix local.hex --force
  - MIX_ENV=test mix deps.get
script:
  - MIX_ENV=test mix ecto.create
  - MIX_ENV=test mix ecto.migrate
  - MIX_ENV=test mix test
